// This file was auto-generated by prisma-generator-typescript-interfaces

export interface User {
  id: number;
  email: string;
  passwordHash: string;
  username: string | null;
  displayName: string | null;
  avatarPath: string | null;
  bio: string | null;
  createdAt: Date;
  updatedAt: Date;
  role: string;
  avatarPosition: string | null;
  backgroundPath: string | null;
  backgroundPosition: string | null;
  ipLocation: string | null;
  favoriteAlbums?: FavoriteAlbum[];
  favoriteSongs?: FavoriteSong[];
  feedPosts?: FeedPost[];
  feedPostComments?: FeedPostComment[];
  feedPostLikes?: FeedPostLike[];
  followers?: Follow[];
  following?: Follow[];
  followedArtists?: FollowedArtist[];
  friendOf?: Friendship[];
  friendships?: Friendship[];
  sentMessages?: Message[];
  notifications?: Notification[];
  playHistories?: PlayHistory[];
  playlists?: UserPlaylist[];
  settings?: UserSettings | null;
  conversations?: Conversation[];
}

export interface Follow {
  id: number;
  followerId: number;
  followingId: number;
  createdAt: Date;
  following?: User;
  follower?: User;
}

export interface FeedPost {
  id: number;
  userId: number;
  content: string | null;
  type: string;
  targetId: number | null;
  createdAt: Date;
  images: string | null;
  user?: User;
  comments?: FeedPostComment[];
  likes?: FeedPostLike[];
}

export interface FeedPostLike {
  id: number;
  postId: number;
  userId: number;
  createdAt: Date;
  user?: User;
  post?: FeedPost;
}

export interface FeedPostComment {
  id: number;
  postId: number;
  userId: number;
  content: string;
  createdAt: Date;
  user?: User;
  post?: FeedPost;
}

export interface UserSettings {
  id: number;
  userId: number;
  theme: string;
  audioQuality: string;
  autoPlay: boolean;
  notifications: boolean;
  user?: User;
}

export interface FavoriteSong {
  id: number;
  userId: number;
  songId: number;
  createdAt: Date;
  song?: Song;
  user?: User;
}

export interface FavoriteAlbum {
  id: number;
  userId: number;
  albumId: number;
  createdAt: Date;
  album?: Album;
  user?: User;
}

export interface FollowedArtist {
  id: number;
  userId: number;
  artistId: number;
  createdAt: Date;
  artist?: Artist;
  user?: User;
}

export interface PlayHistory {
  id: number;
  userId: number;
  songId: number;
  playedAt: Date;
  duration: number | null;
  completed: boolean;
  song?: Song;
  user?: User;
}

export interface UserPlaylist {
  id: number;
  userId: number;
  name: string;
  description: string | null;
  coverPath: string | null;
  isPublic: boolean;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
  songs?: UserPlaylistSong[];
}

export interface UserPlaylistSong {
  id: number;
  playlistId: number;
  songId: number;
  position: number;
  addedAt: Date;
  song?: Song;
  playlist?: UserPlaylist;
}

export interface Artist {
  id: number;
  name: string;
  avatarUrl: string | null;
  headerUrl: string | null;
  bio: string | null;
  bioImageUrl: string | null;
  avatarPosition: string | null;
  backgroundPosition: string | null;
  followers?: FollowedArtist[];
  albums?: Album[];
}

export interface Album {
  id: number;
  title: string;
  uniqueId: string;
  coverPath: string | null;
  favoritedBy?: FavoriteAlbum[];
  songs?: Song[];
  artists?: Artist[];
}

export interface Song {
  id: number;
  title: string;
  trackNumber: number | null;
  path: string;
  albumId: number;
  duration: number | null;
  lyrics: string | null;
  favoritedBy?: FavoriteSong[];
  playHistories?: PlayHistory[];
  album?: Album;
  userPlaylistSongs?: UserPlaylistSong[];
  playlists?: Playlist[];
  messages?: Message[];
}

export interface Playlist {
  id: number;
  name: string;
  description: string | null;
  createdAt: Date;
  songs?: Song[];
}

export interface Notification {
  id: string;
  userId: number;
  title: string;
  message: string;
  type: string;
  isRead: boolean;
  createdAt: Date;
  user?: User;
}

export interface Friendship {
  id: number;
  userId: number;
  friendId: number;
  status: string;
  createdAt: Date;
  friend?: User;
  user?: User;
}

export interface Conversation {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  messages?: Message[];
  participants?: User[];
}

export interface Message {
  id: number;
  conversationId: number;
  senderId: number;
  content: string;
  type: string;
  imagePath: string | null;
  songId: number | null;
  isRead: boolean;
  createdAt: Date;
  sender?: User;
  conversation?: Conversation;
  song?: Song | null;
}
